---
name: CD (Snapshot deployment)

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: sonatype-nexus-snapshots
          server-username: NEXUS_REPO_USER
          server-password: NEXUS_REPO_PASSWORD

      - name: deploy code
        env:
          NEXUS_REPO_USER: ${{ secrets.NEXUS_REPO_USER }}
          NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
          MAVEN_ARGS: "-B -fae"
        run: |
          make deploy
